### ISSUE TITLE
Instalation issue

### ISSUE THREAD

**Issue by awrelll** [g0v/gitbook-plugin-discourse#1]
What would be an example of "parent_category_id": PARENT_CATEGORY_ID, i can't seem to figure it out in my discourse backend.

Thanks!

**Comment by audreyt** [comment]
Hi! Once you create a category, it'll have an URL like https://talk.vtaiwan.tw/c/6-category.json — the `6` is the ID.

If you have assigned the category a short name, such as https://talk.vtaiwan.tw/c/personal-data-protection, add a `.json` to the URL and see https://talk.vtaiwan.tw/c/personal-data-protection.json for the `category_id` field (which is `22` in this example.)
